networks:
  default:
    name: internal
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16
          gateway: 172.10.0.1

services:
  wireguard-sts:
    image: linuxserver/wireguard:latest
    container_name: wireguard-sts
    environment:
      TZ: $TZ
    volumes:
      - $APPDATA/wireguard-sts:/config
    ports:
      - "61820:51820/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv4.conf.all.src_valid_mark: 1
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.10.0.100
